# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 6f933bd
_src_path: .
default_branch: main
docs: mkdocs
package_name: sample_project
project_name: Sample Project
remote: github
remote_url: git@github.com:jannismain/python-project-template-example.git
use_bumpversion: true
use_precommit: true
user_name: jannismain
